### ISSUE TITLE
How to call the orientation functions

### ISSUE THREAD

**Issue by borhademohini** [feedhenry/fh-cordova-plugin-orientation#1]
How to call the orientation functions

**Comment by wei-lee** [comment]
You can set orientation like this:

``` javascript
window.plugins.deviceOrientation. setOrientation('landscape', success, fail);
```

But this plugin hasn't been updated for a long time and hasn't been tested against the latest version of iOS & Android, it may not work anymore.

**Comment by borhademohini** [comment]
okay I will try.

But can you suggest me some updated version of the plugins serving for the same purpose.

**Comment by wei-lee** [comment]
I am not really sure. TBH, even this isn't working, shouldn't be too hard to fix the issues anyway.

**Comment by borhademohini** [comment]
okay.

**Comment by camilamacedo86** [comment]
Closing since it is open for a long time now. Shows already solved and the project is deprecated.
